// src/app/layout.js (server component)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper"; // client wrapper that decides whether to render AppShell

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trucking Management Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ClientWrapper decides whether to render the AppShell (Navbar + Sidebar) or only the page (login, etc.) */}
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
